#!/bin/bash

echo "Enter project name:"
read project

echo "Enter author name:"
read author

if [ -z "$project" ] || [ -z "$author" ]; then
  echo "Project name and author required."
  exit 1
fi

date_today=$(date +"%Y-%m-%d")

base="$project"
src="$base/src"
inc="$base/include"

mkdir -p "$src" "$inc" "$base/build"

# README
cat > "$base/README.md" <<EOF
# $project
Author: $author
Created on: $date_today

A simple C project scaffold generated by Shell.
EOF

# main.c
cat > "$src/main.c" <<EOF
#include <stdio.h>
#include "utils.h"

int main() {
    printf("Hello from $project!\\n");
    greet();
    return 0;
}
EOF

# utils.h
cat > "$inc/utils.h" <<EOF
#ifndef UTILS_H
#define UTILS_H

void greet();

#endif
EOF

# utils.c
cat > "$src/utils.c" <<EOF
#include <stdio.h>
#include "utils.h"

void greet() {
    printf("Greetings from utils!\\n");
}
EOF

echo "Project $project generated successfully!"
